const TYPE_TOGGLE_FORM = 'TOGGLE_FORM';
const TYPE_SET_FILTER_MODE = 'SET_FILTER_MODE';
const TYPE_FETCH_TOGGLE_WORD = 'TYPE_FETCH_TOGGLE_WORD';
const TYPE_FETCH_REMOVE_WORD = 'TYPE_FETCH_REMOVE_WORD';
const TYPE_FETCH_ALL_WORD = 'TYPE_FETCH_ALL_WORD';
const TYPE_FETCH_INSERT_WORD = 'TYPE_FETCH_INSERT_WORD';

export default {
  TYPE_TOGGLE_FORM,
  TYPE_SET_FILTER_MODE,
  TYPE_FETCH_TOGGLE_WORD,
  TYPE_FETCH_REMOVE_WORD,
  TYPE_FETCH_ALL_WORD,
  TYPE_FETCH_INSERT_WORD,
};
