const TYPE_ADD_WORD = 'ADD_WORD';
const TYPE_TOGGLE_FORM = 'TOGGLE_FORM';
const TYPE_SET_FILTER_MODE = 'SET_FILTER_MODE';
const TYPE_TOGGLE_WORD = 'TOGGLE_WORD';
const TYPE_REMOVE_WORD = 'REMOVE_WORD';

export default {
  TYPE_ADD_WORD,
  TYPE_TOGGLE_FORM,
  TYPE_SET_FILTER_MODE,
  TYPE_TOGGLE_WORD,
  TYPE_REMOVE_WORD,
};
